Repository supercollider/supercollider, pull requests merged in 2018-04, with the labels that each got.

#3620 RangerSlider: fix setSpan, setDeviation
  SCClassLibrary/Common/GUI/Base/QRangeSlider.sc
  testsuite/classlibrary/TestRangeSlider.sc
Labels: comp: Qt GUI

#3632 Contributing.md: add more info on ways to contribute
  CONTRIBUTING.md
Labels: comp: project docs

#3633 issue #3401: File.copy crashes interpreter when destination exists
  lang/LangPrimSource/PyrFilePrim.cpp
Labels: comp: class library

#3647 Readme - update slack invite link
  README.md
Labels: comp: project docs

#3643 PyrLexer: expand "~" in pathnames in passOne_processDir
  lang/LangSource/PyrLexer.cpp
Labels: comp: sclang

#3660 [IDE] Fix detached docklet visibility bug
  editors/sc-ide/widgets/util/docklet.cpp
  editors/sc-ide/widgets/util/docklet.hpp
Labels: env: SCIDE

#3429 Add pseudo-ugen implementation of snap and softRound
  HelpSource/Classes/UGen.schelp
  SCClassLibrary/Common/Audio/UGen.sc
Labels: comp: sclang

#3634 classlib: fix String methods that use path separators
  HelpSource/Classes/String.schelp
  SCClassLibrary/Common/Collections/String.sc
  testsuite/classlibrary/TestString.sc
Labels: API change, comp: class library, os: Windows

#3681 Help: FFT-Overview: Replace auto-pvcopy example, and explain
  HelpSource/Guides/FFT-Overview.schelp
Labels: comp: help

#3668 [docs] - supercollider/supercollider/README_LINUX.md - fixing tiny little issues with grammar, punctuation and other issues
  README_LINUX.md
Labels: comp: project docs

#3645 filter OSC response based on bufnum
  HelpSource/Classes/Buffer.schelp
  SCClassLibrary/Common/Control/Buffer.sc
  testsuite/classlibrary/TestQuery.sc
Labels: bug, comp: class library

#3700 classlib: patch String:+/+
  HelpSource/Classes/String.schelp
  SCClassLibrary/Common/Collections/String.sc
  testsuite/classlibrary/TestString.sc
Labels: comp: class library

#3672 Topic/add boost primitives
  HelpSource/Classes/Integer.schelp
  HelpSource/Classes/Number.schelp
  HelpSource/Classes/SequenceableCollection.schelp
  HelpSource/Classes/SimpleNumber.schelp
  HelpSource/Guides/Tour-of-Special-Functions.schelp
  SCClassLibrary/Common/Collections/SequenceableCollection.sc
  SCClassLibrary/Common/Math/Integer.sc
  SCClassLibrary/Common/Math/SimpleNumber.sc
  lang/LangPrimSource/PyrMathPrim.cpp
  lang/LangSource/PyrSlot.h
  lang/LangSource/PyrSlot32.h
  lang/LangSource/PyrSlot64.h
Labels: comp: sclang, enhancement
