Repository supercollider/supercollider, pull requests merged in 2018-06, with the labels that each got.

#3165 QT 5.9
  .appveyor.yml
  .travis.yml
  .travis/before-install-linux.sh
  .travis/before-install-osx.sh
  .travis/before-script-linux.sh
  .travis/before-script-osx.sh
  .travis/package-osx.sh
  .travis/qpm-prep.sh
  .travis/test.sh
  CMakeLists.txt
  HelpSource/Classes/Image.schelp
  HelpSource/Classes/View.schelp
  HelpSource/Classes/WebView.schelp
  HelpSource/scdoc.js
  QtCollider/CMakeLists.txt
  QtCollider/Common.h
  QtCollider/QWidgetProxy.cpp
  QtCollider/QcApplication.cpp
  QtCollider/factories.cpp
  QtCollider/hacks/hacks_mac.hpp
  QtCollider/hacks/hacks_mac.mm
  QtCollider/image.h
  QtCollider/interface.cpp
  QtCollider/metatype.cpp
  QtCollider/metatype.hpp
  QtCollider/primitives/prim_QImage.cpp
  QtCollider/primitives/prim_QPen.cpp
  QtCollider/primitives/prim_misc.cpp
  QtCollider/style/ProxyStyle.cpp
  QtCollider/type_codec.cpp
  QtCollider/type_codec.hpp
  QtCollider/widgets/BasicWidgets.h
  QtCollider/widgets/QcCanvas.cpp
  QtCollider/widgets/QcCanvas.h
  QtCollider/widgets/QcListWidget.h
  QtCollider/widgets/QcScopeShm.cpp
  QtCollider/widgets/QcWebView.cpp
  QtCollider/widgets/QcWebView.h
  QtCollider/widgets/image_painter.h
  QtCollider/widgets/web_page.cpp
  QtCollider/widgets/web_page.hpp
  SCClassLibrary/Common/GUI/Base/QCallback.sc
  SCClassLibrary/Common/GUI/Base/QImage.sc
  SCClassLibrary/Common/GUI/Base/QWebView.sc
  SCClassLibrary/Common/GUI/Base/enums.sc
  SCClassLibrary/deprecated/3.10/QWebView.sc
  cmake_modules/MacOSXBundleInfo.plist.in
  editors/sc-ide/CMakeLists.txt
  editors/sc-ide/core/main.cpp
  editors/sc-ide/widgets/code_editor/sc_editor.cpp
  editors/sc-ide/widgets/help_browser.cpp
  editors/sc-ide/widgets/help_browser.hpp
  editors/sc-ide/widgets/main_window.cpp
  editors/sc-ide/widgets/style/style.cpp
  lang/CMakeLists.txt
Labels: comp: Qt GUI, comp: class library

#3761 readme: add licensing info
  README.md
Labels: comp: project docs

#3770 class lib: Fix "nonexistent class extension" errors in non-Qt builds
  SCClassLibrary/deprecated/3.10/GUI/QWebView.sc
  SCClassLibrary/deprecated/3.9/GUI/HistoryGui.sc
  SCClassLibrary/deprecated/3.9/GUI/WiiMoteGUI.sc
Labels: comp: class library

#3751 sclang: fix windows defaultSystemAppSupportDirectory
  common/SC_Filesystem_win.cpp
Labels: comp: sclang, os: Windows

#3765 docs: mouse(Up|Down)Action
  HelpSource/Classes/Document.schelp
  HelpSource/Classes/TextView.schelp
  HelpSource/Classes/View.schelp
Labels: comp: help

#3786 Fix a maths bug in expexp() in MiscInlineMath.h
  lang/LangSource/MiscInlineMath.h
Labels: comp: sclang

#3767 Revise Linux README
  README_LINUX.md
Labels: comp: help

#3787 IDE: add space after colon in autocompletion
  editors/sc-ide/widgets/code_editor/autocompleter.cpp
Labels: env: SCIDE

#3779 class library: Add bar graph mode to PlotView
  HelpSource/Classes/Plotter.schelp
  SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc
Labels: comp: class library

#3774 sclang: fixes crash on call to Array::lace with empty subarrays
  lang/LangPrimSource/PyrArrayPrimitives.cpp
  testsuite/classlibrary/TestArray.sc
Labels: comp: sclang

#3686 QtGUI: Remove scroll wheel check for scrollbars in Windows and Linux
  QtCollider/style/ProxyStyle.cpp
Labels: comp: Qt GUI

#3763 appveyor: update to vs2017
  .appveyor.yml
Labels: comp: appveyor

#3720 remove remaining unsafe usage of sf_open
  QtCollider/widgets/soundfileview/view.cpp
  QtCollider/widgets/soundfileview/view.hpp
  common/SC_SndFileHelpers.hpp
  lang/LangPrimSource/PyrFilePrim.cpp
  server/scsynth/SC_SequencedCommand.cpp
  server/scsynth/SC_SequencedCommand.h
  server/scsynth/SC_World.cpp
  server/supernova/audio_backend/sndfile_backend.hpp
  server/supernova/sc/sc_plugin_interface.cpp
  server/supernova/server/buffer_manager.cpp
Labels: comp: Qt GUI, comp: sclang, comp: scsynth, comp: supernova

#3738 Add NO_X11 build option for headless plugins compilation
  CMakeLists.txt
  server/plugins/CMakeLists.txt
Labels: comp: build, enhancement

#3788 Classlib: Recorder: Create user's recording directory if it doesn't exist
  HelpSource/Classes/Recorder.schelp
  HelpSource/Classes/Server.schelp
  SCClassLibrary/Common/Control/Recorder.sc
Labels: comp: class library

#3772 sclang: Fix excessive calls to SC_TerminalClient::tick when SC_QT is off
  lang/LangSource/SC_TerminalClient.cpp
Labels: comp: sclang

#3804 sclang: fix hang on floating point arguments to Integer:forBy
  lang/LangSource/PyrInterpreter3.cpp
  testsuite/classlibrary/TestInteger.sc
Labels: comp: sclang

#3803 sclang: fix issues in dumpByteCodes
  lang/LangSource/dumpByteCodes.cpp
Labels: comp: sclang

#3707 Some fixes for boost special functions
  HelpSource/Classes/Integer.schelp
  HelpSource/Classes/SequenceableCollection.schelp
  HelpSource/Classes/SimpleNumber.schelp
  HelpSource/Guides/Tour-of-Special-Functions.schelp
  SCClassLibrary/Common/Collections/SequenceableCollection.sc
  SCClassLibrary/Common/Math/Integer.sc
Labels: comp: class library

#3816 ide: fix help browser reload button
  editors/sc-ide/widgets/help_browser.cpp
Labels: env: SCIDE

#3790 Latency compensation in scsynth & supernova
  server/scsynth/SC_Jack.cpp
  server/supernova/audio_backend/jack_backend.hpp
  server/supernova/audio_backend/portaudio_backend.hpp
  server/supernova/sc/sc_osc_handler.hpp
  server/supernova/server/server.hpp
Labels: comp: scsynth, comp: supernova

#3754 ServerOptions:asOptionsString: fix to use correct concatenation
  HelpSource/Classes/Platform.schelp
  SCClassLibrary/Common/Control/Server.sc
  SCClassLibrary/Platform/Platform.sc
  SCClassLibrary/Platform/windows/WindowsPlatform.sc
  server/scsynth/scsynth_main.cpp
  server/supernova/server/server_args.cpp
Labels: bug, comp: sclang

#3810 build: Ensure CMake only finds Qt 5.7+
  QtCollider/CMakeLists.txt
  editors/sc-ide/CMakeLists.txt
  lang/CMakeLists.txt
Labels: comp: build

#3741 Node.release should handle negative release times
  HelpSource/Classes/Node.schelp
  SCClassLibrary/Common/Control/Node.sc
  testsuite/classlibrary/TestNode.sc
  testsuite/classlibrary/TestNode_Server.sc
Labels: comp: class library, enhancement

#2504 Add Qt menu support
  HelpSource/Classes/CustomViewAction.schelp
  HelpSource/Classes/MainMenu.schelp
  HelpSource/Classes/Menu.schelp
  HelpSource/Classes/MenuAction.schelp
  HelpSource/Classes/ToolBar.schelp
  HelpSource/Classes/View.schelp
  QtCollider/CMakeLists.txt
  QtCollider/Common.h
  QtCollider/QcApplication.cpp
  QtCollider/QcApplication.h
  QtCollider/QcWidgetFactory.h
  QtCollider/factories.cpp
  QtCollider/layouts/layouts.cpp
  QtCollider/layouts/layouts.hpp
  QtCollider/metatype.cpp
  QtCollider/primitives/prim_misc.cpp
  QtCollider/type_codec.cpp
  QtCollider/type_codec.hpp
  QtCollider/widgets/BasicWidgets.h
  QtCollider/widgets/QcButton.cpp
  QtCollider/widgets/QcButton.h
  QtCollider/widgets/QcMenu.cpp
  QtCollider/widgets/QcMenu.h
  QtCollider/widgets/QcScrollArea.cpp
  QtCollider/widgets/QcScrollArea.h
  QtCollider/widgets/QcTreeWidget.cpp
  QtCollider/widgets/QcTreeWidget.h
  SCClassLibrary/Common/GUI/Base/BasicViews.sc
  SCClassLibrary/Common/GUI/Base/Menu.sc
  SCClassLibrary/Common/GUI/Base/QView.sc
  SCClassLibrary/Common/GUI/Base/enums.sc
Labels: API change, comp: Qt GUI, enhancement

#3815 supernova: Unify scsynth/supernova plugin loading
  common/SC_Filesystem.hpp
  server/CMakeLists.txt
  server/scsynth/CMakeLists.txt
  server/scsynth/SC_Lib_Cintf.cpp
  server/supernova/CMakeLists.txt
  server/supernova/sc/sc_ugen_factory.cpp
  server/supernova/server/main.cpp
Labels: comp: supernova
