Repository supercollider/supercollider, pull requests merged in 2019-03, with the labels that each got.

#4333 Help: Classes/FFT should highlight correct multichannel approach
  HelpSource/Classes/FFT.schelp
Labels: comp: help

#4341 Plugins: Convolution2_Ctor: Remove incorrect prevtrig init line
  server/plugins/Convolution.cpp
Labels: bug, comp: server plugins

#4185 Fix build using system boost/ system yaml-cpp
  CMakeLists.txt
  editors/sc-ide/CMakeLists.txt
  external_libraries/CMakeLists.txt
  lang/CMakeLists.txt
  server/CMakeLists.txt
  server/plugins/CMakeLists.txt
  server/scsynth/CMakeLists.txt
  server/supernova/CMakeLists.txt
  testsuite/server/CMakeLists.txt
  testsuite/server/supernova/CMakeLists.txt
Labels: comp: build

#4344 Properly manager Server in TestSanitize
  testsuite/classlibrary/TestSanitize.sc
Labels: comp: UnitTest

#4345 TestFloat: handle "-nan" in test
  testsuite/classlibrary/TestFloat.sc
Labels: comp: UnitTest

#4346 TestCoreUGens: replace Server.default
  testsuite/classlibrary/TestCoreUGens.sc
Labels: comp: UnitTest
