Repository supercollider/supercollider, pull requests merged in 2020-12, with the labels that each got.

#5273 GHA: add github actions for linux and macos
  .github/workflows/actions-test.yml
Labels: comp: build

#5263 Make Jack Startup environment variables usable.
  HelpSource/Classes/LinuxPlatform.schelp
  HelpSource/Reference/AudioDeviceSelection.schelp
  SCClassLibrary/Platform/linux/LinuxPlatform.sc
Labels: comp: class library, comp: help, os: Linux

#5277 Classlib: SynthDesc should produce a valid rate symbol for DUGens
  SCClassLibrary/Common/Audio/SynthDesc.sc
Labels: bug, comp: class library

#5280 github actions: re-add linux gcc5 build
  .github/workflows/actions.yml
Labels: comp: build

#5281 GHA: refresh ccache daily, add homebrew download cache
  .github/workflows/actions.yml
Labels: comp: CI/CD

#5300 Don't sign macOS builds in CI
  .github/workflows/actions.yml
  .travis/before-script-osx.sh
Labels: comp: CI/CD, comp: build

#5298 scsynth: use CoreAudio host time to calculate time of day offset
  server/scsynth/SC_CoreAudio.cpp
Labels: comp: scsynth, os: macOS

#5302 travis: fix latest develop link
  .travis.yml
Labels: comp: CI/CD
