Repository supercollider/supercollider, pull requests merged in 2020-11, with the labels that each got.

#5216 qtcollider: QcSignalSpy prevent creating QVariant<QVariant>
  QtCollider/QcSignalSpy.h
  QtCollider/widgets/QcWebView.cpp
Labels: comp: sclang, qt5

#5230 cmake: with macOS+QtWebEngine+Qt5.15.1, mark all manually deployed files writeable
  editors/sc-ide/CMakeLists.txt
Labels: comp: build, os: macOS

#5212 clang-format.py: handle binary files better
  tools/clang-format.py
Labels: organizational

#5234 travis: fix macos latest develop download link
  .travis.yml
Labels: comp: travis, os: macOS

#5237 cherry pick #5234 (travis: fix macos latest develop download link)
  .travis.yml
Labels: comp: travis

#5220 class library: add Complex:-sqrt
  HelpSource/Classes/Complex.schelp
  SCClassLibrary/Common/Math/Complex.sc
Labels: comp: class library

#5242 help browser: fix crash on exit with qt 5.9.3 build
  editors/sc-ide/widgets/help_browser.cpp
Labels: env: SCIDE, os: macOS

#5243 update version+changelog for 3.11.2
  CHANGELOG.md
  SCVersion.txt
Labels: organizational

#5245 Merge 3.11 into master
  .appveyor.yml
  .gitignore
  .travis.yml
  .travis/before-install-osx.sh
  .travis/package-osx.sh
  CHANGELOG.md
  HelpSource/Classes/Dictionary.schelp
  HelpSource/Classes/LFSaw.schelp
  HelpSource/Classes/MIDIFunc.schelp
  HelpSource/Classes/MIDIdef.schelp
  HelpSource/Classes/NotificationCenter.schelp
  HelpSource/Classes/Onsets.schelp
  HelpSource/Classes/Pattern.schelp
  HelpSource/Classes/Set.schelp
  HelpSource/Classes/SortedList.schelp
  HelpSource/Guides/UsingMIDI.schelp
  HelpSource/Reference/AudioDeviceSelection.schelp
  HelpSource/Tutorials/Getting-Started/10-SynthDefs-and-Synths.schelp
  HelpSource/Tutorials/Getting-Started/11-Busses.schelp
  HelpSource/Tutorials/Getting-Started/15-Sequencing-with-Routines-and-Tasks.schelp
  HelpSource/editor.js
  QtCollider/factories.cpp
  QtCollider/widgets/QcWebView.cpp
  QtCollider/widgets/QcWebView.h
  README.md
  SCClassLibrary/Common/Audio/SynthDesc.sc
  SCClassLibrary/Common/Control/Recorder.sc
  SCClassLibrary/Common/GUI/Base/QWebView.sc
  SCClassLibrary/Common/GUI/tools/HelpBrowser.sc
  SCClassLibrary/Common/Streams/FilterPatterns.sc
  SCClassLibrary/Common/Streams/Patterns.sc
  SCClassLibrary/Common/Streams/TimePatterns.sc
  SCClassLibrary/Common/UnitTesting/UnitTest.sc
  SCClassLibrary/JITLib/ProxySpace/ProxySpace.sc
  SCVersion.txt
  cmake_modules/FindPortaudio.cmake
  editors/sc-ide/CMakeLists.txt
  editors/sc-ide/widgets/help_browser.cpp
  editors/sc-ide/widgets/help_browser.hpp
  external_libraries/CMakeLists.txt
  server/scsynth/SC_Audio_Android.cpp
  server/scsynth/SC_CoreAudio.h
  server/supernova/sc/sc_osc_handler.cpp
  testsuite/classlibrary/TestPattern.sc
  testsuite/classlibrary/TestProxySpace.sc
  testsuite/classlibrary/TestServer.sc
  testsuite/classlibrary/TestSynthDescMetadata.sc
  tools/release/git_utilities.py
  tools/release/make_release.py
  tools/release/requirements.txt
  tools/release/utilities.py
Labels: organizational

#5200 sclang: MIDI realtime messages: Push correct number of values onto the stack
  lang/LangPrimSource/SC_PortMIDI.cpp
Labels: comp: sclang, os: Windows

#5250 note about default sample rate on Windows
  HelpSource/Classes/ServerOptions.schelp
  HelpSource/Reference/AudioDeviceSelection.schelp
Labels: comp: help

#5238 class library: don't warn by default when sending SynthDef
  HelpSource/Classes/SynthDef.schelp
  SCClassLibrary/Common/Audio/SynthDef.sc
Labels: comp: class library

#5254 Improve doxygen style documentation in header files for plugin developers
  include/plugin_interface/SC_Constants.h
  include/plugin_interface/SC_InlineBinaryOp.h
  include/plugin_interface/SC_InlineUnaryOp.h
  include/plugin_interface/SC_RGen.h
Labels: comp: help, comp: server plugins

#5110 scsynth: macOS: clip values on hw out busses
  HelpSource/Classes/ServerOptions.schelp
  SCClassLibrary/Common/Control/Server.sc
  include/server/ErrorMessage.hpp
  include/server/SC_OSC_Commands.h
  include/server/SC_WorldOptions.h
  server/scsynth/SC_CoreAudio.cpp
  server/scsynth/SC_CoreAudio.h
  server/scsynth/SC_World.cpp
  server/scsynth/scsynth_main.cpp
Labels: comp: scsynth, os: macOS

#5269 Merge 3.11 into develop
  HelpSource/Tutorials/Getting-Started/10-SynthDefs-and-Synths.schelp
Labels: organizational
