Repository supercollider/supercollider, pull requests merged in 2021-03, with the labels that each got.

#5376 exclude a specific failing test in TestProxyNodeMap
  testsuite/scripts/gha_test_run_proto.json
Labels: comp: test suite

#5380 gha: change the main action's name
  .github/workflows/actions.yml
Labels: comp: CI/CD

#5381 README.md: add link to github actions, remove appveyor badge
  README.md
Labels: comp: project docs

#5377 GitHub Actions: add Windows builds
  .github/workflows/actions.yml
  CMakeLists.txt
  cmake_modules/FindSndfile.cmake
Labels: comp: CI/CD

#5378 Remove AppVeyor
  .appveyor.yml
Labels: comp: CI/CD

#5384 GitHub Actions: use qt5 on macOS
  .github/workflows/actions.yml
Labels: comp: CI/CD

#5385 Update README.md with information about current build environment
  README.md
Labels: comp: project docs

#5388 Make verify_app optional, improve rpath setting
  .github/workflows/actions.yml
  CMakeLists.txt
  editors/sc-ide/CMakeLists.txt
  lang/CMakeLists.txt
Labels: comp: build, os: macOS, qt5

#5390 cmake: fix verify_app switch
  editors/sc-ide/CMakeLists.txt
Labels: comp: build, os: macOS

#5389 GitHub Actions: add macOS legacy build
  .github/workflows/actions.yml
  editors/sc-ide/CMakeLists.txt
Labels: comp: CI/CD

#5392 3.11 -> develop
  HelpSource/Classes/EnvGen.schelp
  HelpSource/Reference/NodeProxy_roles.schelp
Labels: comp: help, organizational

#5397 Bela: various fixes
  README_BELA.md
  README_LINUX.md
  server/plugins/BelaUGens.cpp
Labels: os: Bela

#5307 ContiguousBlockAllocator cleanup (code style, help)
  HelpSource/Classes/ContiguousBlockAllocator.schelp
  SCClassLibrary/Common/Control/Engine.sc
  SCClassLibrary/deprecated/3.12/deprecated-3.12.sc
Labels: comp: class library, comp: help

#5357 Fix bug where sclang hangs forever when exiting
  lang/LangPrimSource/PyrSched.cpp
Labels: comp: sclang

#5402 docs: remove use of sc3-plugins ugen
  HelpSource/Guides/Non-Realtime-Synthesis.schelp
Labels: comp: help

#5393 Servers: workaround for boost interprocess
  CMakeLists.txt
Labels: comp: scsynth, comp: supernova, os: Windows

#5407 help: Fix instances of "the the"
  HelpSource/Classes/Bus.schelp
  HelpSource/Classes/Document.schelp
  HelpSource/Classes/EZNumber.schelp
  HelpSource/Classes/EZRanger.schelp
  HelpSource/Classes/EZSlider.schelp
  HelpSource/Classes/MIDIFunc.schelp
  HelpSource/Classes/Process.schelp
  HelpSource/Classes/SCContainerView.schelp
  HelpSource/Classes/Synth.schelp
  HelpSource/Guides/More-On-Getting-Help.schelp
  HelpSource/Guides/Order-of-execution.schelp
  HelpSource/Reference/Server-Command-Reference.schelp
  HelpSource/Reference/Synth-Definition-File-Format.schelp
  HelpSource/Tutorials/Getting-Started/13-Buffers.schelp
  HelpSource/Tutorials/Mark_Polishook_tutorial/15_Groups.schelp
  HelpSource/Tutorials/Mark_Polishook_tutorial/22_Runtime_errors.schelp
Labels: comp: help
