Repository supercollider/supercollider, pull requests merged in 2021-04, with the labels that each got.

#5409 GHA: install necessary compilers
  .github/workflows/actions.yml
Labels: comp: CI/CD

#5283 Create dmg for macOS artifacts
  .github/workflows/actions.yml
Labels: comp: CI/CD

#5396 Increase required C++ standard to C++17
  .github/workflows/actions.yml
  CMakeLists.txt
  README.md
  README_LINUX.md
  README_MACOS.md
  README_WINDOWS.md
  SCDoc/CMakeLists.txt
  SCDoc/lex.scdoc.cpp
  server/supernova/CMakeLists.txt
  tools/cmake_gen/generate_server_plugin_cmake.py
Labels: comp: CI/CD, comp: build, comp: other

#5415 GitHub Actions: fix macOS s3 upload
  .github/workflows/actions.yml
Labels: comp: CI/CD, os: macOS

#5423 README_LINUX.md: add note about headless operation
  README_LINUX.md
Labels: comp: project docs, os: Linux

#5422 gha testsuite: remove environment variable
  .github/workflows/actions.yml
Labels: comp: CI/CD
