Repository supercollider/supercollider, pull requests merged in 2022-11, with the labels that each got.

#5901 Fix .sqrt and .reciprocal on the server on M1 CPUs
  server/plugins/UnaryOpUGens.cpp
Labels: os: macOS, comp: server plugins

#5522 fix parsing block arguments bug
  lang/LangSource/Bison/lang11d
  lang/LangSource/Bison/lang11d_tab.cpp
  lang/LangSource/Bison/lang11d_tab.h
Labels: comp: sclang

#5903 Update CHANGELOG.md for 3.13.0-rc1
  CHANGELOG.md
  HelpSource/Guides/News-3_13.schelp
  HelpSource/Help.schelp
Labels: comp: project docs
