Repository supercollider/supercollider, pull requests merged in 2023-08, with the labels that each got.

#6061 Help: DiskIn/Out should link also to VDiskIn
  HelpSource/Classes/DiskIn.schelp
  HelpSource/Classes/DiskOut.schelp
Labels: comp: help

#6070 Ignore vscode files
  .gitignore
Labels: organizational

#6069 testsuite: skip TestThreadReschedule in GHA
  testsuite/scripts/test_run_proto_gha.scd
Labels: comp: CI/CD
