Repository supercollider/supercollider, pull requests merged in 2023-02, with the labels that each got.

#5951 Update SCVersion.txt for 3.13.0-rc2
  SCVersion.txt
Labels: organizational

#5950 Update SCVersion on develop
  SCVersion.txt
Labels: organizational

#5944 Update the Changelogs for 3.13.0-rc2
  CHANGELOG.md
  HelpSource/Guides/News-3_13.schelp
Labels: comp: help, comp: project docs

#5943 Cherry-pick #1 for 3.13.0-rc2
  HelpSource/Reference/Server-Command-Reference.schelp
  SCClassLibrary/Common/Control/Buffer.sc
  cmake_modules/FindJack.cmake
  server/scsynth/CMakeLists.txt
  server/supernova/CMakeLists.txt
Labels: organizational

#5954 LINUX_README.md: add information for Fedora
  README_LINUX.md
Labels: comp: project docs

#5952 GHA: use updated ccache directory on Linux
  .github/workflows/actions.yml
Labels: comp: CI/CD

#5953 GHA: create macOS universal binary with homebrew libraries
  .github/workflows/actions.yml
  CHANGELOG.md
  HelpSource/Guides/News-3_13.schelp
Labels: comp: CI/CD

#5960 GHA: update artifact name for upload to AWS S3
  .github/workflows/actions.yml
Labels: comp: CI/CD

#5959 Merge 3.13 to develop
  .github/workflows/actions.yml
  CHANGELOG.md
  HelpSource/Classes/AbstractGridLines.schelp
  HelpSource/Classes/Collection.schelp
  HelpSource/Classes/Plotter.schelp
  HelpSource/Classes/Quark.schelp
  HelpSource/Classes/Quarks.schelp
  HelpSource/Classes/Signal.schelp
  HelpSource/Classes/SimpleNumber.schelp
  HelpSource/Guides/News-3_13.schelp
  HelpSource/Guides/UsingQuarks.schelp
  README_LINUX.md
  SCClassLibrary/Common/Control/Spec.sc
  SCClassLibrary/Common/GUI/Base/Grid.sc
  SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc
  SCClassLibrary/Common/Geometry/Rect.sc
  SCClassLibrary/Common/Quarks/Quark.sc
  SCClassLibrary/Common/Quarks/Quarks.sc
  testsuite/classlibrary/TestQuark.sc
  testsuite/classlibrary/assets/TestQuark/TestQuark.quark
Labels: organizational

#5965 Poll: fix initialization to fire on first-sample trigger
  server/plugins/TriggerUGens.cpp
Labels: comp: server plugins

#5966 Update Changelogs and SCVersion for 3.13.0-rc3
  .github/workflows/actions.yml
  CHANGELOG.md
  HelpSource/Guides/News-3_13.schelp
  SCVersion.txt
Labels: organizational

#5976 GHA macOS: temporary fix for the legacy build
  .github/workflows/actions.yml
Labels: comp: CI/CD

#5979 Updates for 3.13.0
  CHANGELOG.md
  HelpSource/Guides/News-3_13.schelp
  SCVersion.txt
Labels: organizational

#5981 Merge main into develop after 3.13.0 release
  .github/workflows/actions.yml
  CHANGELOG.md
  HelpSource/Guides/News-3_13.schelp
  SCClassLibrary/Common/Streams/Stream.sc
  server/plugins/TriggerUGens.cpp
Labels: organizational

#5984 GHA: use Xcode 10.3 for macOS legacy build
  .github/workflows/actions.yml
Labels: comp: CI/CD

#5977 GHA: fix logic for installing Qt from homebrew
  .github/workflows/actions.yml
Labels: comp: CI/CD
