Repository supercollider/supercollider, pull requests merged in 2023-04, with the labels that each got.

#5747 Refactor SC_ComPort, add support for receiving raw UDP socket communication
  HelpSource/Classes/Main.schelp
  SCClassLibrary/DefaultLibrary/Main.sc
  lang/LangPrimSource/OSCData.cpp
  lang/LangPrimSource/SC_ComPort.cpp
  lang/LangPrimSource/SC_ComPort.h
  lang/LangPrimSource/SC_Msg.h
  testsuite/classlibrary/TestNetAddr.sc
Labels: enhancement, comp: sclang

#6002 macOS: raise legacy build OS requirement to 10.11
  .github/workflows/actions.yml
  README.md
Labels: os: macOS, comp: CI/CD

#6004 GHA: update Ubuntu 18.04 jobs
  .github/workflows/actions.yml
Labels: comp: CI/CD

#6005 GHA Windows: revert ccache version
  .github/workflows/actions.yml
Labels: comp: CI/CD

#4696 Topic/document save
  HelpSource/Classes/Document.schelp
  SCClassLibrary/scide_scqt/ScIDE.sc
  editors/sc-ide/core/doc_manager.cpp
  editors/sc-ide/core/doc_manager.hpp
  testsuite/classlibrary/TestDocument.sc
Labels: comp: sclang, env: SCIDE, comp: help

#6003 Run testsuite directly
  .github/workflows/actions.yml
  README.md
  testsuite/classlibrary/CommonTests.quark
  testsuite/classlibrary/TestSerialPort.sc
  testsuite/classlibrary/TestThreadReschedule.sc
  testsuite/scripts/add_include_path.scd
  testsuite/scripts/gha_test_run_proto.json
  testsuite/scripts/print_results.scd
  testsuite/scripts/sclang_test_runner.scd
  testsuite/scripts/test_run_proto_all.scd
  testsuite/scripts/test_run_proto_gha.scd
Labels: comp: testing, comp: CI/CD
