Repository supercollider/supercollider, pull requests merged in 2024-12, with the labels that each got.

#6123 ScIDE : post window : clear button
  editors/sc-ide/widgets/post_window.cpp
Labels: env: SCIDE

#6530 ClassLib: Make Pbind work with kwargs
  HelpSource/Classes/Pbind.schelp
  SCClassLibrary/Common/Streams/Patterns.sc
  testsuite/classlibrary/TestPattern.sc
Labels: comp: class library, comp: help

#6555 GHA: move macOS tests to the latest OS
  .github/workflows/actions.yml
  .github/workflows/test_macos.yml
  README.md
Labels: os: macOS, comp: CI/CD

#6557 GHA: fix caching on macOS
  .github/workflows/build_macos.yml
Labels: os: macOS, comp: CI/CD

#6556 Fix `incompatible-pointer-types` warning/error for portmidi
  CMakeLists.txt
  external_libraries/portmidi/pm_win/pmwinmm.c
Labels: comp: 3rd party

#6546 Do not change indentation within multiline comments
  editors/sc-ide/widgets/code_editor/highlighter.cpp
  editors/sc-ide/widgets/code_editor/sc_editor.cpp
  editors/sc-ide/widgets/code_editor/tokens.hpp
Labels: env: SCIDE, has merge note

#6558 GHA workflow: move the definition of artifacts
  .github/workflows/actions.yml
  .github/workflows/test_linux.yml
  .github/workflows/test_macos.yml
  .github/workflows/test_windows.yml
Labels: comp: CI/CD

#6561 Add monokai theme
  HelpSource/scdoc.js
  HelpSource/themes/monokai.css
  editors/sc-ide/core/settings/default_themes.cpp
  editors/sc-ide/core/settings/theme.cpp
  editors/sc-ide/core/settings/theme.hpp
Labels: env: SCIDE

#6472 Dedicated lint workflow to verify all files in CI
  .github/workflows/lint_non_code.yml
Labels: comp: CI/CD

#6521 QtCollider: QcTreeWidget: fix instance methods
  QtCollider/widgets/QcTreeWidget.h
Labels: bug, env: SCIDE, qt6

#6559 Restart server for each RTAlloc test
  testsuite/classlibrary/TestUGen_RTAlloc.sc
Labels: comp: class library, comp: testing, comp: CI/CD

#6570 [qt5] QMetaType fix for Qt5
  QtCollider/QObjectProxy.cpp
  QtCollider/QcObjectFactory.h
  QtCollider/metatype.hpp
Labels: comp: Qt GUI, qt5

#6452 ClassLib: fix nil.addAll returning original collection instead of a copy
  SCClassLibrary/Common/Core/Nil.sc
Labels: comp: class library
