Repository supercollider/supercollider, pull requests merged in 2024-10, with the labels that each got.

#6504 lang: add isxdigit definition
  lang/CMakeLists.txt
Labels: os: Windows, comp: build

#6191 improve/fix plugin unloading
  HelpSource/Guides/WritingUGens.schelp
  include/plugin_interface/SC_InterfaceTable.h
  server/plugins/DiskIO_UGens.cpp
  server/plugins/UIUGens.cpp
  server/plugins/UIUGens.mm
  server/scsynth/SC_Lib_Cintf.cpp
Labels: enhancement, comp: server plugins, API extension

#6475 Migrate to Qt6
  .github/workflows/build_linux.yml
  .github/workflows/build_macos.yml
  .github/workflows/build_windows.yml
  .github/workflows/test_linux.yml
  QtCollider/CMakeLists.txt
  QtCollider/QObjectProxy.cpp
  QtCollider/QcObjectFactory.h
  QtCollider/QcSignalSpy.h
  QtCollider/factories.cpp
  QtCollider/interface.cpp
  QtCollider/metatype.hpp
  QtCollider/primitives/prim_misc.cpp
  QtCollider/primitives/primitives.cpp
  QtCollider/type_codec.hpp
  QtCollider/widgets/QcNumberBox.cpp
  QtCollider/widgets/QcWebView.cpp
  QtCollider/widgets/QcWebView.h
  editors/sc-ide/CMakeLists.txt
  editors/sc-ide/core/doc_manager.cpp
  editors/sc-ide/core/main.cpp
  editors/sc-ide/core/main.hpp
  editors/sc-ide/core/main_function.cpp
  editors/sc-ide/widgets/code_editor/editor.cpp
  editors/sc-ide/widgets/help_browser.cpp
  editors/sc-ide/widgets/lookup_dialog.cpp
  editors/sc-ide/widgets/post_window.cpp
  editors/sc-ide/widgets/settings/editor_page.cpp
  editors/sc-ide/widgets/util/icon_list_widget.hpp
  lang/CMakeLists.txt
Labels: comp: 3rd party, comp: CI/CD, qt6, has merge note

#6483 [qt6] update project docs
  README.md
  README_LINUX.md
  README_MACOS.md
  README_WINDOWS.md
Labels: comp: project docs, has merge note, blocked

#6489 GHA: update build matrix
  .github/workflows/actions.yml
  .github/workflows/build_linux.yml
  .github/workflows/build_macos.yml
  .github/workflows/build_windows.yml
  README.md
Labels: comp: CI/CD

#6510 Update README_LINUX.md
  README_LINUX.md
Labels: os: Linux, comp: project docs

#6513 Help: replace esoteric syntax in Pbind help file.
  HelpSource/Classes/Pbind.schelp
Labels: comp: help

#6516 List failed tests before the results
  testsuite/scripts/print_results.scd
Labels: comp: testing

#6518 GHA: don't run weekly
  .github/workflows/actions.yml
Labels: comp: CI/CD

#6491 [tests] TestCoreUGen updates
  testsuite/classlibrary/TestCoreUGens.sc
Labels: comp: testing

#6511 CMake: fix qt6 detection
  QtCollider/CMakeLists.txt
Labels: comp: build, qt6

#6519 scide style.cpp: fix icon sizes on tab bar and help toolbar
  editors/sc-ide/widgets/style/style.cpp
Labels: bug, qt6

#6522 Update testsuite printing result(s)
  testsuite/scripts/print_results.scd
Labels: comp: testing
