Repository supercollider/supercollider, pull requests merged in 2025-09, with the labels that each got.

#7115 Add interval notation guide in random section of SimpleNumber.schelp
  HelpSource/Classes/SimpleNumber.schelp
Labels: comp: help

#7145 GHA: Update macOS legacy build runner
  .github/workflows/build_macos.yml
Labels: comp: CI/CD

#7133 SCLang: avoid collecting inside primitives
  lang/LangPrimSource/PyrPrimitive.cpp
  lang/LangSource/GC.cpp
  lang/LangSource/GC.h
Labels: comp: sclang

#7146 build: cleanup portaudio cmake integration
  cmake_modules/FindPortaudio.cmake
  external_libraries/portaudio/CMakeLists.txt
  lang/CMakeLists.txt
  server/scsynth/CMakeLists.txt
  server/supernova/CMakeLists.txt
Labels: comp: build, comp: 3rd party, squash on merge

#7079 Fix schelp warnings in SC3.14.0
  CHANGELOG.md
  HelpSource/Classes/Document.schelp
  HelpSource/Classes/DoesNotUnderstandError.schelp
  HelpSource/Classes/EnvironmentRedirect.schelp
  HelpSource/Classes/MultiOutUGen.schelp
  HelpSource/Classes/SimpleNumber.schelp
Labels: comp: help, has merge note, squash on merge
