Repository supercollider/supercollider, pull requests merged in 2025-01, with the labels that each got.

#6576 Boost 1.87 support
  QtCollider/LanguageClient.cpp
  lang/LangPrimSource/OSCData.cpp
  lang/LangPrimSource/PyrSerialPrim.cpp
  lang/LangPrimSource/SC_ComPort.cpp
  lang/LangPrimSource/SC_ComPort.h
  lang/LangSource/SC_TerminalClient.cpp
  lang/LangSource/SC_TerminalClient.h
  server/scsynth/SC_ComPort.cpp
  server/supernova/sc/sc_osc_handler.hpp
  server/supernova/utilities/osc_server.hpp
Labels: comp: 3rd party, comp: CI/CD

#6575 QtCollider: Fix touchpad mousewheel event scaling
  QtCollider/QWidgetProxy.cpp
Labels: comp: Qt GUI

#6175 [plugins] EnvGen: fix initialization
  HelpSource/Classes/Env.schelp
  SCClassLibrary/Common/Audio/Env.sc
  server/plugins/LFUGens.cpp
  testsuite/classlibrary/TestCoreUGens.sc
Labels: comp: scsynth

#6587 Fix Pwalk boundary behavior when using directionPattern for folding
  SCClassLibrary/Common/Streams/ListPatterns.sc
  testsuite/classlibrary/TestPattern.sc
Labels: bug, comp: class library

#6586 Fix block allocator 'reserve' for start addresses in the middle of a free range
  SCClassLibrary/Common/Control/Engine.sc
  testsuite/classlibrary/TestContiguousBlockAllocator.sc
Labels: bug, comp: class library

#6590 Fix asio post invocation for `SC_TerminalClient`
  lang/LangSource/SC_TerminalClient.cpp
Labels: bug, comp: sclang, comp: 3rd party

#6593 Add macOS arm nightly build upload to s3
  .github/workflows/actions.yml
Labels: os: macOS, comp: CI/CD
