Repository supercollider/supercollider, pull requests merged in 2025-10, with the labels that each got.

#7151 Add NSMotionUsageDescription for AirPod positional tracking support
  cmake_modules/MacOSXBundleInfo.plist.in
Labels: os: macOS, comp: build

#7159 classlib: nodeproxy: init filter role inside a synthdef
  SCClassLibrary/JITLib/ProxySpace/wrapForNodeProxy.sc
Labels: comp: class library, comp: JITlib

#7165 tests: disable process creation tests on windows
  testsuite/scripts/test_run_proto_gha.scd
Labels: os: Windows, comp: testing

#7154 SCLang: fix disable collect in primitives
  lang/LangPrimSource/PyrPrimitive.cpp
Labels: comp: sclang

#7178 Remove GITHUB_TOKEN from actions.yml
  .github/workflows/actions.yml
Labels: comp: CI/CD
