Repository supercollider/supercollider, pull requests merged in 2025-07, with the labels that each got.

#7024 classlib: Post: Remove reference to the 18-years-deleted '.flush' method
  SCClassLibrary/Common/Streams/IOStream.sc
Labels: bug, comp: class library

#6942 GHA: use all cores on linux build
  .github/workflows/build_linux.yml
Labels: comp: CI/CD

#7011 Add nil's behaviour in Set and Nil documentation
  HelpSource/Classes/Nil.schelp
  HelpSource/Classes/Set.schelp
  SCClassLibrary/Common/Collections/Set.sc
Labels: comp: help

#7025 clarified use of supernova and fixed build instructions with qt5
  README_MACOS.md
Labels: comp: project docs, squash on merge

#7028 Update SCIde.schelp
  HelpSource/Guides/SCIde.schelp
Labels: comp: help

#6993 Help: update guides to reflect kwargs.
  HelpSource/Classes/Function.schelp
  HelpSource/Classes/IdentityDictionary.schelp
  HelpSource/Guides/ObjectPrototyping.schelp
  HelpSource/Guides/WritingClasses.schelp
  HelpSource/Reference/Functions.schelp
Labels: comp: help

#7026 Guide: Special functions: correct bounds, code formatting, appearance
  HelpSource/Guides/Tour-of-Special-Functions.schelp
Labels: comp: help

#7033 Increase font size of status box
  editors/sc-ide/widgets/util/status_box.cpp
Labels: bug, env: SCIDE, squash on merge

#7021 sclang: protect method lookup from out of bounds index
  lang/LangPrimSource/PyrPrimitive.cpp
  lang/LangSource/PyrMessage.cpp
Labels: comp: sclang, has merge note

#7030 QtCollider: AbstractStepValue widgets: improve wheelEvent scroll behavior + fix regression
  QtCollider/widgets/QcAbstractStepValue.h
  QtCollider/widgets/QcKnob.cpp
  QtCollider/widgets/QcKnob.hpp
  QtCollider/widgets/QcNumberBox.cpp
  QtCollider/widgets/QcNumberBox.h
  QtCollider/widgets/QcSlider.cpp
  QtCollider/widgets/QcSlider.h
  QtCollider/widgets/QcSlider2D.cpp
  QtCollider/widgets/QcSlider2D.h
  editors/sc-ide/widgets/audio_status_box.cpp
Labels: comp: Qt GUI, env: SCIDE, Work In Progress (WIP) - don't merge yet, squash on merge

#7045 clarify build instructions with qt5 on macOS (#7025)
  README_MACOS.md
Labels: organizational

#7036 IDE: don't call resize(0, 0) on completion widget
  editors/sc-ide/widgets/code_editor/completion_menu.cpp
Labels: env: SCIDE

#7048 improve wasapi line on markdown changelog as well
  CHANGELOG.md
Labels: comp: project docs

#6976 help: kwargs
  HelpSource/Classes/Fdef.schelp
  HelpSource/Classes/Function.schelp
  HelpSource/Classes/FunctionDef.schelp
  HelpSource/Classes/Maybe.schelp
  HelpSource/Classes/Object.schelp
  HelpSource/Classes/Pbind.schelp
Labels: comp: help, Work In Progress (WIP) - don't merge yet

#7050 Merge 3.14.0-rc2 into develop
  CHANGELOG.md
  HelpSource/Classes/Function.schelp
  HelpSource/Classes/IdentityDictionary.schelp
  HelpSource/Classes/SinOsc.schelp
  HelpSource/Guides/News-3_14.schelp
  HelpSource/Guides/ObjectPrototyping.schelp
  HelpSource/Guides/UGen-Changelog.schelp
  HelpSource/Guides/WritingClasses.schelp
  HelpSource/Reference/Functions.schelp
  QtCollider/widgets/QcAbstractStepValue.h
  QtCollider/widgets/QcKnob.cpp
  QtCollider/widgets/QcKnob.hpp
  QtCollider/widgets/QcNumberBox.cpp
  QtCollider/widgets/QcNumberBox.h
  QtCollider/widgets/QcSlider.cpp
  QtCollider/widgets/QcSlider.h
  QtCollider/widgets/QcSlider2D.cpp
  QtCollider/widgets/QcSlider2D.h
  editors/sc-ide/widgets/audio_status_box.cpp
  editors/sc-ide/widgets/code_editor/completion_menu.cpp
  editors/sc-ide/widgets/util/status_box.cpp
Labels: organizational

#7012 classlib: helpFileForMethod jumps to method
  SCClassLibrary/DefaultLibrary/dumpFullInterface.sc
Labels: comp: SCDoc

#7054 Correct typo in `News in SuperCollider version 3.14`
  HelpSource/Guides/News-3_14.schelp
Labels: comp: help

#6997 classlib: DoesNotUnderstandError: refactor suggestions
  HelpSource/Classes/Class.schelp
  HelpSource/Classes/Object.schelp
  HelpSource/Classes/String.schelp
  SCClassLibrary/Common/Collections/String.sc
  SCClassLibrary/Common/Core/Error.sc
  SCClassLibrary/Common/Core/Kernel.sc
  SCClassLibrary/Common/GUI/Base/EZgui.sc
  lang/LangPrimSource/PyrPrimitive.cpp
  lang/LangSource/PyrPrimitiveProto.h
  testsuite/classlibrary/TestClass.sc
  testsuite/classlibrary/TestDoesNotUnderstandError.sc
Labels: comp: class library, has release note, squash on merge

#7066 sclang / qt: fix positioning of non-resizable windows.
  QtCollider/widgets/QcWindow.cpp
Labels: comp: Qt GUI

#7069 Adjust the bottom position of the FreqScope and the bottom position of the ServerMeter for all platforms (a clean PR)
  HelpSource/Classes/Window.schelp
  SCClassLibrary/Common/GUI/Base/QWindow.sc
  SCClassLibrary/Common/GUI/PlusGUI/Control/FreqScope.sc
  SCClassLibrary/Common/GUI/tools/ServerMeter.sc
Labels: comp: class library, has merge note

#7068 sclang:Bag: override .copy
  SCClassLibrary/Common/Collections/Bag.sc
  testsuite/classlibrary/TestBag.sc
Labels: comp: class library

#7056 Insert an empty line after server boot
  SCClassLibrary/Common/Control/Server.sc
Labels: comp: class library, has merge note, squash on merge

#7051 Fix default device selection on Windows when no WASAPI devices are available
  common/SC_PaUtils.cpp
Labels: comp: scsynth, comp: supernova, os: Windows

#7072 Add changelog for 3.14.0-rc3
  CHANGELOG.md
  HelpSource/Guides/News-3_14.schelp
Labels: organizational

#7073 Merge 3.14.0-rc3 to develop
  CHANGELOG.md
  HelpSource/Classes/Fdef.schelp
  HelpSource/Classes/Function.schelp
  HelpSource/Classes/FunctionDef.schelp
  HelpSource/Classes/Maybe.schelp
  HelpSource/Classes/Object.schelp
  HelpSource/Classes/Pbind.schelp
  HelpSource/Guides/News-3_14.schelp
  SCClassLibrary/Common/Collections/Dictionary.sc
  common/SC_PaUtils.cpp
  testsuite/classlibrary/TestIdentityDictionaryObjectPrototyping.sc
Labels: organizational

#7074 Correct a typo in SinOsc.schelp (#7064)
  HelpSource/Classes/SinOsc.schelp
Labels: comp: help
